name: Infrastructure Drift Detection

on:
  schedule:
    - cron: '0 6 * * 1-5'  # Executa de segunda a sexta às 6h
  workflow_dispatch:  # Permite execução manual

jobs:
  drift-detection:
    name: Detecção de Drift da Infraestrutura
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]
    environment: ${{ matrix.environment }}
    env:
      TF_WORKSPACE: ${{ matrix.environment }}
      AWS_REGION: us-east-1
      TF_VERSION: 1.5.7
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: cd terraform/environments/${{ matrix.environment }} && terraform init

      - name: Verificar Drift
        id: plan
        run: |
          cd terraform/environments/${{ matrix.environment }}
          terraform plan -detailed-exitcode -out=tfplan
          echo "EXITCODE=$?" >> $GITHUB_ENV
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_STAGING }}
          TF_VAR_stripe_api_key: ${{ secrets.STRIPE_API_KEY_STAGING }}
        continue-on-error: true

      - name: Notificar Drift Detectado
        if: env.EXITCODE == '2'
        uses: 8398a7/action-slack@v3
        with:
          status: 'warning'
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: "⚠️ Drift detectado no ambiente ${{ matrix.environment }}! A infraestrutura atual difere do estado desejado no Terraform."
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
